#!/usr/bin/env node
/**
 * Embeds the webview assets (real .js / .css files under webview/) into
 * src/webview/generated.ts so the extension host can inline them into the
 * webview HTML with syntax checking available at authoring time.
 *
 * Usage:
 *   node scripts/embed-webview.mjs            # generate once
 *   node scripts/embed-webview.mjs --watch    # regenerate on file changes
 */
import { readFileSync, watchFile, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "src", "webview", "generated.ts");

const ASSETS = {
  dashboardScript: "webview/dashboard-script.js",
  dashboardStyle: "webview/dashboard-style.css",
  momentsScript: "webview/moments-script.js",
  momentsStyle: "webview/moments-style.css",
};

function buildGenerated() {
  const parts = [
    "// AUTO-GENERATED by scripts/embed-webview.mjs — do not edit by hand.",
    "// Run `bun run embed:webview` to regenerate.",
    "",
  ];
  for (const [name, rel] of Object.entries(ASSETS)) {
    const content = readFileSync(join(root, rel), "utf8");
    parts.push(`export const ${name} = ${JSON.stringify(content)};`);
  }
  parts.push("");
  return parts.join("\n");
}

function generate() {
  const next = buildGenerated();
  writeFileSync(outFile, next, "utf8");
  console.log(`[embed-webview] wrote ${outFile} (${next.length} bytes)`);
}

const watch = process.argv.includes("--watch");
generate();

if (watch) {
  console.log("[embed-webview] watching webview/ for changes...");
  const targets = Object.values(ASSETS).map((rel) => join(root, rel));
  for (const target of targets) {
    watchFile(target, { interval: 500 }, () => {
      try {
        generate();
      } catch (error) {
        console.error("[embed-webview] regeneration failed:", error);
      }
    });
  }
}
